{% set name = "pixman" %}
{% set version = "0.40.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cairographics.org/releases/{{ name }}-{{ version }}.tar.gz
  sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc

build:
  number: 2
  run_exports:
    # excellent: add new symbols sometimes, none removed.
    #    https://abi-laboratory.pro/tracker/timeline/pixman/
    - {{ pin_subpackage('pixman') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - meson
    - ninja-base
    - pkg-config

test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/pkgconfig/pixman-1.pc  # [not win]   

    - if not exist %LIBRARY_BIN%\\pixman-1-0.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pixman-1.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\pixman-1.pc exit 1  # [win]
    

about:
  home: https://www.pixman.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'A low-level software library for pixel manipulation.'
  description: |
    Pixman is a low-level software library for pixel manipulation, providing
    features such as image compositing and trapezoid rasterization.
  dev_url: https://gitlab.freedesktop.org/pixman/pixman
  doc_url: https://gitlab.freedesktop.org/pixman/pixman

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - katietz
