travis:
  secure:
    BINSTAR_TOKEN: VvWImLD0YALjjlIsA7BHxM23x24C52ckzTO3k7YcjyJ8VrKzWijTimAgQVxoDPkcGkwmgegSZ5514O1kEi2YOV15aehLscfKmsNLez8pmgNUqBn+a38VUZ9A85cmhwevVnqu27W/BUGlcqLQ9E1Xlz3tcjBjXQbGQg8MLyvrotL3evpi+1mh0IKXDrvorO33MDi27BpEL0FeVzR+k7hY1HWE31881liIYMwx7TeN0fZNgTzWQCLk8Iz20pOQvnECSeGiGeBg8pYdud2ml6HejCaiR+O+s3MhQsYwK9Ls54qrFmnrcnE856Q/+mfD+GlZfO84W1G7Pe+phXYB+y031+P5eSI8GucldWuCiX0Xl82wmyP5i1xF5i6Jgy+fc8Ws2/Wl0+Hi+18XjJzxkuVKDpmfS/ERYW/iyZ5fSqdPW0dKM+tjrHdS0SB3iYgXxnl040rsOseqhALQX7oziqODIAHp0TfyhVei+uekRW0uFyI1BHC+hmAVxyaEs36LwGwoXMLs0yRoLBt/bd0Hb7QlvKuVVbQ0lVzNQyLyIigM8abw5mbybgMaZ0fcXSSK8ybWIjx//Ac/bW11i+2fuwuDcYLuAb/wkkKcoZWWYTEH1wTdvu4YSf6A+Mj1fLrOVLp9Z9kaDffAfbvQgt0ydPFSkIRMEZdhTwyRaRDen8YyZBg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
