travis:
  secure:
    BINSTAR_TOKEN: S0FtjDBsiAsLi8YDm9Px1KYvpjHJxEIjUPKRDYRUaHDJ9Nv6+JQt5yFV0s12pNAJhN8G/JG5HfdwLQH3OAZQzv+QE+jbaVgrA5sof/NLVTZMmz3XZl01xXrlW3YRMzA9tWZNUBh83tlDCO1sMbJRVbGsY7XDvThoRGrCuaaBg+Dwa4BoZT+ygBhryI0ngoLxTI+UWEbLOS1VqTRwQOgyOjHC9sUqfsLnDQFMmSlaCRFlMhvVMu4NMhoDC+IS+VX4VM/9mT++ob3CUHhvNCDNb+UwpPheVn2Nkkpf59idKqCKJt85XegGdxy6nWaV4RXGSdP07r9jlHG1fwUya38B8UkdLWoVZtqmH0Ku11NMTZiA+bRhgACavXsZ/22GpBRKOvVc6FOIIHpcxAcAK8UyBWPnEBv/9piTY7jJfAZvw3ySA6ROVHr2iTxsDbWfh4x3BdsYb10ySEY9BNzuKqt5cWr9ROZY1dohsq0QhHk02vh+5+Mcke/eBzdep7o9W1sV9BJjCtAcUQFq5IZzarO+hKvWHx92KrlnBskgK86HtnUro9mHN+F02YtE1wA7nDIrbfU8mZ5RBzs7DvkrupUik3jwLSDWSojaDXbV07XKz6MrkUKXbok6YyPVwQT1ccG+5vvvIcltImUlgLKyMqV5KfiTcyCPzHZWny98fI6eBrM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
